### ISSUE TITLE
Syntax errors for errors in script

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#10]
No idea how involved this feature request is, but it would be great if wrong Small Basic scripts would produce errors, instead of the parser failing silently. For example, a message like "Error on line XYZ" would be a big help for beginners, and with longer scripts.

**Comment by wixette** [comment]
@ratkingsminion does Engine.ErrorInfo work for the case?

See https://github.com/wixette/isb/blob/main/unity_integration_demo/Assets/Scripts/Program.cs

```
        if (engine.Compile(code, true) && engine.Run(true))
        {
            // ...
        }
        else
        {
            var buffer = new List<string>();
            foreach (var content in engine.ErrorInfo.Contents)
            {
                buffer.Add(content.ToDisplayString());
            }
            PrintDebugInfo(string.Join("\n", buffer));
        }
```

See also https://github.com/wixette/isb/blob/main/csharp/ISB/Utilities/DiagnosticBag.cs

**Comment by ratkingsminion** [comment]
Oh, yes, that works much better. Seems I forgot to copy some of your example code...

Though, it seems a problem remains: showing errors in that way works well for the REPL, but due to missing line numbers you get a load of errors, but have no hint where they are happening.

**Comment by wixette** [comment]
Diagnostics.Range is designed for recording and returning the error location. That's a feature inherited from Microsoft's original Small Basic design. Every error instance in the DiagnosticBag has its own Range info.

Please see https://github.com/wixette/isb/blob/main/csharp/ISB/Utilities/Diagnostic.cs and let me know if there are any issues.

**Comment by ratkingsminion** [comment]
Thanks for the clarifications!
