### ISSUE TITLE
Not using value returned by method freezes Unity

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#12]
What the title says - if you have a method that returns a value, and the SmallBasic script doesn't somehow catch it, it freezes Unity. (In my test case I return a new StringValue("True") or new StringValue("False")).

```
object.MethodReturningSomething() 'freezes
foo = object.MethodReturningSomething() 'doesn't freeze
```

EDIT: Unity already freezes if I just add a string on its own line

```
"Test" 'freezes
```

EDIT2: This only seems to happen when the code is within a subroutine. I also tried it in the integration demo.

**Comment by wixette** [comment]
Confirmed and accepted. The following SmallBasic code stuck the execution of the engine:

```
sub x
  "test"
endsub
x()
```
