### ISSUE TITLE
boolean values

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#14]
In Microsoft Small Basic, the following code

```
If 0 Then
  TextWindow.WriteLine(0)
EndIf
If 1 Then
  TextWindow.WriteLine(1)
EndIf
If "True" Then
  TextWindow.WriteLine("True")
EndIf
If "False" Then
  TextWindow.WriteLine("False")
EndIf
If "Anything" Then
  TextWindow.WriteLine("Anything")
EndIf
```

only prints "True". In ISB, the same conditions prints "1", "True", "False" and "Anything". Is there a reason why the result is so vastly different from the original language?

**Comment by wixette** [comment]
It was my personal preference when designing the implicit-conversion-to-boolean feature for ISB. The current behavior of ISB is similar to [Python's choice](http://anh.cs.luc.edu/handsonPythonTutorial/boolean.html). For example:

```python
Python 3.9.7 (default, Sep  3 2021, 12:37:55) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> if 0: print(0)
... 
>>> if 1: print(1)
... 
1
>>> if "True": print("True")
... 
True
>>> if "False": print("False")
... 
False
>>> if "Anything": print("Anything")
... 
Anything
>>> 
```

It is also similar to JavaScript's conversions. For example:

```JavaScript
Boolean(0) // false
Boolean(1) // true
Boolean("True") // true
Boolean("False") // true
Boolean("Anything") // true
```

And even more examples in other scripting languages...

MSB's design looked a bit "old-fashioned" to me considering "modern" designs of the feature.

**Comment by ratkingsminion** [comment]
Understood! I guess what I'm really missing is documentation of such differences.

**Comment by ratkingsminion** [comment]
Two other things I wondered about:

a) There is a special BooleanValue type for ISB, but there doesn't seem to exist True/False for the actual SB scripts. Is there specific reason?

b) Would it be possible to add the Not operator to ISB?

I'm asking because I might use ISB for scripting support for people who don't do much programming otherwise, and code like

```
If obj.MethodReturningBool() <> 1 Then
```

doesn't look very intuitive.

**Comment by wixette** [comment]
Yes, both of them make sense for logical expressions. I will get them ready.

To document the feature differences between ISB and MSB is also important.

Will track the progress with this issue.

**Comment by wixette** [comment]
Both Boolean literals and the "not" logical operator are supported. E.g.:

```BASIC
filename = "abc.txt"
a = (not string.startswith(filename, ".") and string.endswith(filename, ".txt"))
print(a)
if a = True then
  print(filename)
endif
```

As for the doc improvement, I will track it with a separate issue, at https://github.com/wixette/isb/issues/17

Closing this issue.
