### ISSUE TITLE
Comparing strings always returns true

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#25]
In the integration demo, the following code adds a sphere:
```
If "foo" = "bar" Then
	Game.AddBall(1, 1, 1)
EndIf
```
Is string comparison supported in ISB, or am I doing something wrong?

**Comment by wixette** [comment]
Good catch. That's a thing that I forgot to made.

**Comment by wixette** [comment]
Microsft Small Basic only supports equal/non-equal comparisons for strings:

Equal comparison cases:

```
"a" = "a" -> true
"a" = "b" -> false
"3" = "3" -> true
"3" = 3 -> true
"3" = "4" -> false
"3" = 4 -> false
```

As for ">", "<", ..., MSB only supports comparisons between numbers:

```
"3" > 2 -> true
"3" > "2" -> true
"3" > 4 -> false
"3" > "4" -> false
```

And fails at string comparisons:

```
"b" > "a" -> false   // NOT FRIENDLY TO PROGRMMERS
```

**Comment by wixette** [comment]
With https://github.com/wixette/isb/pull/26 the string comparisons of ISB behave the same as MSB.
