### ISSUE TITLE
Type of an unitialised variable

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#27]
It seems to be String?
I have this simple program:

```
For i = 0 To 10
   x = x + 1
   xyz.Print(x)
EndFor
```

With MS SmallBasic, this prints the numbers 1 to 11; in ISB it's 1, 11, 111, 1111, 11111 .... - Of course I can just write x = 0 at the beginning, but I wondered if this actually wanted, or rather some kind of bug.

**Comment by wixette** [comment]
There is a slight difference between ISB and MSB when adding an empty/uninitialized value to a number.

It is reasonable to be compatible with MSB here I guess.
