### ISSUE TITLE
Missing Resources.resources when targeting WebGL

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#31]
Hallo, I currently got back to experiment with Small Basic and WebGL, and I noticed that I wouldn't get any compilation error messages from ISB. The dev console of my browser prints this whenever I try it:

`MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "ISB.Properties.Resources.resources" was correctly embedded or linked into assembly "ISB" at compile time, or that all the satellite assemblies required are loadable and fully signed.`

**Comment by wixette** [comment]
This link https://docs.unity3d.com/es/2021.1/Manual/webgl-embeddedresources.html explains the reason and provides a solution on Unity side:

> By default, WebGL builds don’t include embedded resources. This helps to keep the size of the final binary lower, because embedded resources can be rather large. However, some user code and .NET class library APIs depend on the presence of embedded resources to work properly.

I tried the following code they suggested. It works.

```
using UnityEditor;

public class WebGLEditorScript
{
    [MenuItem("WebGL/Enable Embedded Resources")]
    public static void EnableErrorMessageTesting()
    {
        PlayerSettings.SetPropertyBool("useEmbeddedResources", true, BuildTargetGroup.WebGL);
    }
}
```

**Comment by wixette** [comment]
Indeed, .net's embeded string resources are annoying when working together with Unity. I will consider if it's easy to switch to other way to localize string messages.
