### ISSUE TITLE
Empty statements produce errors

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#5]
Not sure if this isn't actually wanted behaviour, but I noticed that this Basic code leads to an error during compilation:

```
a = 1
If a = 1 Then
EndIf
```

The same with

```
While 1
EndWhile
```

**Comment by wixette** [comment]
It's a bug. Fixed with https://github.com/wixette/isb/commit/4bc8ee98f1ff15ed9612cac4e0a2e21a9476726f
