### ISSUE TITLE
ISB not working with WebGL

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#7]
I tried to build my Unity project for WebGL, and while there were no compile errors, I got the runtime error “MissingMethodException: Default constructor not found for type ISB.Lib.BuiltIn.”

Apparently ISB.Lib.BuiltIn's constructor gets stripped away. I solved it by following https://docs.unity3d.com/Manual/ManagedCodeStripping.html and adding an empty Attribute called [Preserve] to the BuiltIn class. Now the interpreter seems to work for WebGL too.

**Comment by wixette** [comment]
Confirmed that ISB.Lib.Builtin is stripped when the IL2CPP backend is used and the `Managed Stripping Level` option is on, no matter which level is selected.

ISB.Lib.Builtin is instantiated via .net reflection. It is failed to be traced by the IL2CPP compiler and be treated as unused code.
